# Generated by Django 4.0.4 on 2022-07-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('part', models.CharField(choices=[('L', 'Length'), ('W', 'Width'), ('D', 'Design')], default='L', max_length=1)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cloth')),
            ],
        ),
    ]
