# Generated by Django 4.0.4 on 2022-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alter',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='alter',
            name='date',
            field=models.DateField(verbose_name='altering date'),
        ),
    ]
