# Generated by Django 4.0.4 on 2022-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessory_alter_alter_options_alter_alter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
